#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Enter Project Name in Workspace Settings                                            #
# Version    : 0.1.19                                                                              #
# Python     : 3.10.10                                                                             #
# Filename   : /config/adapters.yml                                                                #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : Enter URL in Workspace Settings                                                     #
# ------------------------------------------------------------------------------------------------ #
# Created    : Thursday April 20th 2023 01:19:19 pm                                                #
# Modified   : Thursday July 27th 2023 08:50:50 am                                                 #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #
# ------------------------------------------------------------------------------------------------ #
#                                       ID GENERATION                                              #
# ------------------------------------------------------------------------------------------------ #

idgen:
  filepath: admin/idgen.db
  size: 4


# ------------------------------------------------------------------------------------------------ #
#                                        PERSISTENCE                                               #
# ------------------------------------------------------------------------------------------------ #
repo:
  file_visual: repo/visual/
  odb_dataset: repo/dataset.db
  odb_tests: repo/tests.db
  odb_visual: repo/visual.db