#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Enter Project Name in Workspace Settings                                            #
# Version    : 0.1.19                                                                              #
# Python     : 3.10.10                                                                             #
# Filename   : /config/database.yml                                                                #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : Enter URL in Workspace Settings                                                     #
# ------------------------------------------------------------------------------------------------ #
# Created    : Thursday April 20th 2023 01:19:19 pm                                                #
# Modified   : Monday June 5th 2023 04:17:28 pm                                                    #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #
# ------------------------------------------------------------------------------------------------ #
#                                     PERSISTENCE                                                  #
# ------------------------------------------------------------------------------------------------ #
database:
  dev:  explore_db_dev
  prod: explore_db_prod
  test: explore_db_test

# ------------------------------------------------------------------------------------------------ #
#                                     ID STORE                                                     #
# ------------------------------------------------------------------------------------------------ #
idgen: admin/idgen.db